<?php

require_once '/usr/local/www/mint/application/controllers/ControllerModel.php';

/**
 * Test class for ControllerModel.
 * Generated by PHPUnit on 2011-09-20 at 19:13:43.
 */
class ControllerModelTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ControllerModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ControllerModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testIndex().
     */
    public function testIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAdd().
     */
    public function testAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
