<?php

require_once '/usr/local/www/mint/application/core/MintLogger.php';

/**
 * Test class for MintLogger.
 * Generated by PHPUnit on 2011-09-20 at 19:13:35.
 */
class MintLoggerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MintLogger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MintLogger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testLog().
     */
    public function testLog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
