<?php

require_once '/usr/local/www/mint/application/core/MintMenu.php';

/**
 * Test class for MintMenu.
 * Generated by PHPUnit on 2011-09-20 at 19:13:36.
 */
class MintMenuTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MintMenu
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MintMenu;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetByUser().
     */
    public function testGetByUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
