<?php

require_once '/usr/local/www/mint/application/models/MintMutation.php';

/**
 * Test class for MintMutation.
 * Generated by PHPUnit on 2011-09-20 at 19:13:25.
 */
class MintMutationTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MintMutation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new MintMutation;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testEvolve().
     */
    public function testEvolve()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRollback().
     */
    public function testRollback()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
