<?php

require_once '/usr/local/www/mint/application/core/MintEvolution.php';

/**
 * Test class for MintEvolution.
 * Generated by PHPUnit on 2011-09-20 at 19:13:33.
 */
class MintEvolutionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MintEvolution
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MintEvolution;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetFromFile().
     */
    public function testGetFromFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testEvolve().
     */
    public function testEvolve()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRollback().
     */
    public function testRollback()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
