<?php

require_once '/usr/local/www/mint/application/models/MintSession.php';

/**
 * Test class for MintSession.
 * Generated by PHPUnit on 2011-09-20 at 19:13:27.
 */
class MintSessionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MintSession
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MintSession;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetByCookie().
     */
    public function testGetByCookie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
