<?php

require_once '/usr/local/www/mint/application/models/MintACLItem.php';

/**
 * Test class for MintACLItem.
 * Generated by PHPUnit on 2011-09-20 at 19:13:18.
 */
class MintACLItemTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MintACLItem
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MintACLItem;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetByController().
     */
    public function testGetByController()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
