<?php

require_once '/usr/local/www/mint/application/models/MintManager.php';

/**
 * Test class for MintManager.
 * Generated by PHPUnit on 2011-09-20 at 19:13:24.
 */
class MintManagerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MintManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MintManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetByAuth()
    {
        // OK
        $this->assertInstanceOf('MintManager', MintManager::getByAuth('test1', md5('test1')));

        // Wrong password
        $this->assertNull(MintManager::getByAuth('test1', md5('test2')));

        // Empty password
        $this->assertNull(MintManager::getByAuth('test1', md5('')));

        // Null password
        $this->assertNull(MintManager::getByAuth('test1', NULL));

        // Login not exist
        $this->assertNull(MintManager::getByAuth('test199', md5('test2')));
    }
}
?>
