<?php

require_once '/usr/local/www/mint/application/models/MintCustomModelField.php';

/**
 * Test class for MintCustomModelField.
 * Generated by PHPUnit on 2011-09-20 at 19:13:23.
 */
class MintCustomModelFieldTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MintCustomModelField
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MintCustomModelField;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
