<?php

require_once '/usr/local/www/mint/application/models/MintObject.php';

/**
 * Test class for MintObject.
 * Generated by PHPUnit on 2011-09-20 at 19:13:26.
 */
class MintObjectTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MintObject
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MintObject;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetByForeignId().
     */
    public function testGetByForeignId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testExists().
     */
    public function testExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
