<?php

require_once '/usr/local/www/mint/application/core/MintEvolutionException.php';

/**
 * Test class for MintEvolutionException.
 * Generated by PHPUnit on 2011-09-20 at 19:13:34.
 */
class MintEvolutionExceptionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MintEvolutionException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new MintEvolutionException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetSQL().
     */
    public function testGetSQL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
